### ISSUE TITLE
Public profile pageで余分な空間ができる

### ISSUE THREAD

**Issue by yuzulabo** [KnzkDev/mastodon#113]
あまり良くないような

本家:
![ebe32bec712311be864d7611bbef18fc](https://user-images.githubusercontent.com/14953122/34069725-055b9562-e29a-11e7-9965-90d4ae4642d5.png)

Glitch-soc:
![5037bc7ca686d8332d06e22f1d564328](https://user-images.githubusercontent.com/14953122/34069728-0d26cac8-e29a-11e7-85bd-66d4a03163ee.png)

**Comment by ncls7615** [comment]
見にくいしこれも修正かなぁ

**Comment by ncls7615** [comment]
これこういうものだと思えば見にくいということもないし別にこのままでも良いかなーという気はしている…
