### ISSUE TITLE
他のインスタンスでのトゥート表示がおかしい問題

### ISSUE THREAD

**Issue by ncls7615** [KnzkDev/mastodon#61]
# 他のインスタンスでのトゥート表示がおかしい問題
無駄な改行がされてしまうのでそこをどうにかする必要がある気がします。
idk why insert `<p>`
### knzk.meでの表示
![image](https://user-images.githubusercontent.com/28977652/32273801-50bba9e6-bf47-11e7-9ffb-ed483b94601b.png)

### 他インスタンスでの表示
![image](https://user-images.githubusercontent.com/28977652/32273850-8430aa42-bf47-11e7-84f6-1201acc84da6.png)

**Comment by ANNotunzdY** [comment]
他インスタンスだと、サニタイズされてしまうのは仕方ないです。
やれることとしては、無駄な改行がされないようにするくらいかも。

**Comment by ncls7615** [comment]
とりあえず無駄な改行を消していく方向で良いと思う。

**Comment by ncls7615** [comment]
大方の修正は完了しました。
ただまだ若干の不具合があるのでそちらの修正も進めます。

**Comment by ncls7615** [comment]
現状確認されている不具合はすべて修正したので閉じます。
