### ISSUE TITLE
_が一定数以上入るとitalic扱いになる問題

### ISSUE THREAD

**Issue by ncls7615** [KnzkDev/mastodon#62]
# _が一定数以上入るとitalic扱いになる問題
![image](https://user-images.githubusercontent.com/28977652/32273920-d0d53f84-bf47-11e7-9873-81bb8475be34.png)
![image](https://user-images.githubusercontent.com/28977652/32273956-00ffbb6c-bf48-11e7-9f94-360cd55fdcac.png)

### どうするべきか
恐らく"_"でitalicになる機能を殺せば問題ないと思います。

**Comment by mattantonelli** [comment]
Using Redcarpet's `no_intra_emphasis` extension should resolve this. Details on extensions can be found [here](https://github.com/vmg/redcarpet#and-its-like-really-simple-to-use).

```irb
>> markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, no_intra_emphasis: true)
=> #<Redcarpet::Markdown:0x007f7449d2ef28 @renderer=#<Redcarpet::Render::HTML:0x007f7449d2f018 @options={:no_intra_emphasis=>true}>>

>> markdown.render(":an_emoji: test :an_emoji:")
=> "<p>:an_emoji: test :an_emoji:</p>\n"
```

**Comment by ncls7615** [comment]
It worked!!
Thanks for big big big support!!!
![tenor](https://user-images.githubusercontent.com/28977652/32344436-345a3750-c04a-11e7-890f-823f0859d837.gif)
